### ISSUE TITLE
Not supporting Composer2

### ISSUE THREAD

**Issue by mukeshsah08** [davidbarratt/custom-installer#10]
Please update the package to support Composer2.

Thanks!

**Comment by davidbarratt** [comment]
PRs are welcome!

**Comment by suzymasri** [comment]
@davidbarratt PR is ready, kindly review it (#12)

**Comment by davidbarratt** [comment]
Done! This is now in the [1.1.0](https://github.com/davidbarratt/custom-installer/releases/tag/1.1.0) release. Thank you @suzymasri !
